### ISSUE TITLE
Using Unversion

### ISSUE THREAD

**Issue by hotelplan-poornima** [skttl/umbraco-unversion#12]
Hi Matt,

I have installed Unversion to 7.6.4 with the following config. Is there anything else that I need to do to get it working?

<unVersionConfig>
  <add maxDays="90" />
</unVersionConfig>

Poornima

**Comment by leekelleher** [comment]
@hotelplan-poornima Yup, that should be all that's needed to get it working.
Are you experiencing any issues with it?

**Comment by hotelplan-poornima** [comment]
Not exactly issues. Its more kind of working out the correct combination between maxdays and maxcount. Finally set it to just 10 versions and I got it as I expected.

**Comment by leekelleher** [comment]
Cool.  I haven't tried the `MaxDays` config myself, but if you have any issues with it, do let us know.

Thanks!

**Comment by hotelplan-poornima** [comment]
Will do. I think it was the combination that was causing unexpected behaviour. Will test more on my other projects and shall let you know.
