### ISSUE TITLE
UnVersion not working on 7.10.4

### ISSUE THREAD

**Issue by lcichanowicz** [skttl/umbraco-unversion#16]
Greetings.

I just installed UnVersion via the backoffice on a 7.10.4 site.  I want to clear versions from before go-live, which happened on October 3.

Here is my config:
```
<?xml version="1.0"?>
<unVersionConfig>
  <add maxDays="23" />
</unVersionConfig>
```

I tried publishing a few pages, but all of the Rollback versions still show.  I do not see anything in the Umbraco log file related to UnVersion.

Note, I am doing this on a copy of the live site, of course.  Also, I realize I cannot leave that config in place, because it is not a date, it is the number of days.

Thanks,

Lee

**Comment by leekelleher** [comment]
Hi @lcichanowicz, thanks for raising this. _(I've been away on vacation, hence my delayed reply)._

Just checking, has anything changed since you raised this ticket? (In case it started working?)

I haven't tried UnVersion on that specific Umbraco version, so not sure why it wouldn't be working.

**Comment by lcichanowicz** [comment]
Hey, @leekelleher, welcome back.  I hope you feel vacationed.  :]

No, nothing has changed.  My config has been in place the whole time; yet, my rollback for the homepage shows:
![image](https://user-images.githubusercontent.com/4871064/48420874-5cb76b80-e729-11e8-91f8-13d117e659e0.png)
