### ISSUE TITLE
Setup AppVeyor to automatically deploy to MyGet/NuGet

### ISSUE THREAD

**Issue by mattbrailsford** [skttl/umbraco-unversion#8]

**Comment by leekelleher** [comment]
@mattbrailsford I'll help with this... would be great to get a new release out, (specifically for me - I need the #6 fix 😺)

**Comment by leekelleher** [comment]
I've set-up the AppVeyor CI: https://ci.appveyor.com/project/UMCO/umbraco-unversion

Bleeding edge builds are pushing to the community MyGet feed: https://www.myget.org/gallery/umbraco-packages

**Comment by mattbrailsford** [comment]
Wh00p! 👍
